// ─────────────────────────────────────────────────────────────────────────────
// constants.ts — Single source of truth for all Rollin' Munchies business data
// TERRY: Never duplicate this data in components. Import from here always.
// ─────────────────────────────────────────────────────────────────────────────

import type {
  MenuItem,
  MenuCategory,
  LocationEntry,
  HoursEntry,
  SocialLink,
  SiteConfig,
} from '@/types'

// ─── Site Config ─────────────────────────────────────────────────────────────

export const SITE_CONFIG: SiteConfig = {
  name:        "Rollin' Munchies",
  tagline:     'No Seats. Just Good Eats.',
  description: 'Tarboro\'s favorite food truck serving up bold burgers, loaded dogs, and rollin\' fries. Find us on Western Blvd and at local events.',
  phone:       '(252) 907-9660',
  email:       'Rollinmunchiesfamily@gmail.com',
  address: {
    street: '1528 N Main St',
    city:   'Tarboro',
    state:  'NC',
    zip:    '27886',
  },
}

// ─── Hours ────────────────────────────────────────────────────────────────────

export const HOURS: HoursEntry[] = [
  { day: 'Monday',    open: null,     close: null,    closed: true  },
  { day: 'Tuesday',   open: '11:30',  close: '18:00', closed: false },
  { day: 'Wednesday', open: '11:30',  close: '18:00', closed: false },
  { day: 'Thursday',  open: '11:30',  close: '18:00', closed: false },
  { day: 'Friday',    open: '11:30',  close: '18:00', closed: false },
  { day: 'Saturday',  open: '12:00',  close: '18:00', closed: false },
  { day: 'Sunday',    open: null,     close: null,    closed: true  },
]

// ─── Locations ────────────────────────────────────────────────────────────────

export const LOCATIONS: LocationEntry[] = [
  {
    id:          'main',
    label:       'Main Spot',
    address:     '1528 N Main St, Tarboro, NC 27886',
    description: 'Our primary location. Pull up Tue–Sat.',
    coordinates: { lat: 35.9032, lng: -77.5327 },
    isPrimary:   true,
  },
  {
    id:          'reillys',
    label:       "Reilly's",
    address:     '1302 Western Blvd, Tarboro, NC 27886',
    description: 'Catch us parked outside Reilly\'s.',
    coordinates: { lat: 35.8978, lng: -77.5445 },
    isPrimary:   false,
  },
  {
    id:          'dunkin',
    label:       'Behind Tarboro Dunkin\'',
    address:     'Western Blvd, Tarboro, NC',
    description: 'Follow the smoke — we\'re behind Dunkin\'. Until sold out.',
    coordinates: { lat: 35.8975, lng: -77.5441 },
    isPrimary:   false,
  },
]

// ─── Events ───────────────────────────────────────────────────────────────────

export const RECURRING_EVENTS = [
  {
    id:          'wild-wednesdays',
    name:        'Wild Wednesdays Car Show',
    venue:       'Liftking, Tarboro NC',
    description: 'Every Wednesday. Real cars, real food. Come hungry.',
    dayOfWeek:   3, // Wednesday
    recurring:   true,
  },
]

// ─── Menu ─────────────────────────────────────────────────────────────────────

export const MENU_ITEMS: MenuItem[] = [

  // ── Burgers ──────────────────────────────────────────────────────────────────
  {
    id:          'hamburger',
    name:        'Hamburger',
    category:    'burgers',
    description: 'Angus Burger with Mustard, Ketchup, Chili & Onions.',
    price:       5,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        ['classic'],
  },
  {
    id:          'cheeseburger',
    name:        'Cheeseburger',
    category:    'burgers',
    description: 'Angus Burger with Cheese, Mustard, Ketchup, Chili & Onions.',
    price:       6,
    isSignature: false,
    isPopular:   true,
    heatLevel:   0,
    tags:        ['classic'],
  },
  {
    id:          'double-cheeseburger',
    name:        'Double Cheeseburger',
    category:    'burgers',
    description: '2 Angus Burger Patties with Cheese, Mustard, Ketchup, Chili & Onions.',
    price:       10,
    isSignature: false,
    isPopular:   true,
    heatLevel:   0,
    tags:        ['double', 'hearty'],
  },
  {
    id:          'turkey-burger',
    name:        'Turkey Burger',
    category:    'burgers',
    description: 'Mustard, Ketchup, and Onions.',
    price:       9,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'a1-burger',
    name:        'A1 Burger',
    category:    'burgers',
    description: 'A1 Sauce, Cheddar Cheese, & Grilled Onions.',
    price:       7,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'spicy-jack-burger',
    name:        'Spicy Jack Burger',
    category:    'burgers',
    description: 'Peppa Jack Cheese, Grilled Onions, & Mayo.',
    price:       7,
    isSignature: false,
    isPopular:   false,
    heatLevel:   2,
    tags:        ['spicy'],
  },
  {
    id:          'jamaican-jack-burger',
    name:        'Jamaican Jack Burger',
    category:    'burgers',
    description: 'Grilled Onions, Jalapenos, Jerk Sauce, Mayo & Peppa Jack Cheese.',
    price:       8,
    isSignature: true,
    isPopular:   true,
    heatLevel:   2,
    tags:        ['bestseller', 'bold', 'jerk'],
  },
  {
    id:          'pizza-burger',
    name:        'Pizza Burger',
    category:    'burgers',
    description: 'Homemade Marinara Sauce & Mozzarella Cheese.',
    price:       7,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'pepperoni-pizza-burger',
    name:        'Pepperoni Pizza Burger',
    category:    'burgers',
    description: 'Pepperoni, Marinara Sauce & Mozzarella Cheese.',
    price:       8,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'supreme-pizza-burger',
    name:        'Supreme Pizza Burger',
    category:    'burgers',
    description: 'Grilled Pepperoni, Green Peppers, Onions, Marinara & Mozzarella Cheese.',
    price:       9,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        ['loaded'],
  },
  {
    id:          'bacon-cheeseburger',
    name:        'Bacon Cheeseburger',
    category:    'burgers',
    description: 'Bacon, Ketchup, & Mustard.',
    price:       8,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'bacon-cheeseburger-deluxe',
    name:        'Bacon Cheeseburger Deluxe',
    category:    'burgers',
    description: 'Bacon, Ketchup, Mustard, Lettuce, & Pickles.',
    price:       9,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        ['loaded'],
  },
  {
    id:          'cheeseburger-deluxe',
    name:        'Cheeseburger Deluxe',
    category:    'burgers',
    description: 'Ketchup, Mustard, Lettuce, Onions, Pickles, & Tomato.',
    price:       8,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'macdaddy-cheeseburger',
    name:        'MacDaddy Cheeseburger',
    category:    'burgers',
    description: 'Special Sauce, Cheese, Lettuce, Pickles, & Onions.',
    price:       9,
    isSignature: false,
    isPopular:   true,
    heatLevel:   0,
    tags:        ['popular'],
  },
  {
    id:          'jamaican-jack-turkey',
    name:        'Jamaican Jack Turkey Burger',
    category:    'burgers',
    description: 'Turkey Burger, Jerk Sauce, Grilled Onions & Jalapenos, Mayo, & Peppa Jack Cheese.',
    price:       13,
    isSignature: true,
    isPopular:   false,
    heatLevel:   2,
    tags:        ['jerk', 'bold'],
  },
  {
    id:          'bacon-burger-dawg',
    name:        'Bacon Burger Dawg',
    category:    'burgers',
    description: 'Cheeseburger + Nathan\'s Hot Dawg together. Mustard, Ketchup, Chili & Onions.',
    price:       12,
    isSignature: true,
    isPopular:   true,
    heatLevel:   1,
    tags:        ['mashup', 'hearty', 'bestseller'],
  },
  {
    id:          'tims-special',
    name:        "Tim's Special",
    category:    'burgers',
    description: 'Cheeseburger with Mustard, Ketchup & Chili — plus 2 Wangz with your choice of Flava & Fries.',
    price:       13,
    isSignature: true,
    isPopular:   true,
    heatLevel:   1,
    tags:        ['combo', 'bestseller'],
  },
  {
    id:          'blt',
    name:        'B.L.T.',
    category:    'burgers',
    description: 'Bacon, Lettuce, Tomato, & Mayo.',
    price:       5,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        ['classic'],
  },

  // ── Hot Dawg's ────────────────────────────────────────────────────────────────
  {
    id:          'nathans-hot-dawg',
    name:        "Nathan's Hot Dawg",
    category:    'dogs',
    description: 'Ketchup, Mustard, Onions, & Chili.',
    price:       4,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        ['classic'],
  },
  {
    id:          'bacon-dawg',
    name:        'Bacon Dawg',
    category:    'dogs',
    description: 'Cheese, Bacon, & Chili.',
    price:       6,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'cheese-dawg',
    name:        'Cheese Dawg',
    category:    'dogs',
    description: 'Chili, Cheese, & Mayo.',
    price:       5,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'bbq-dawg',
    name:        'BBQ Dawg',
    category:    'dogs',
    description: 'BBQ Sauce, Chili, & Grilled Onions.',
    price:       6,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'texas-dawg',
    name:        'Texas Dawg',
    category:    'dogs',
    description: 'Chili, Cheese, & Jalapenos.',
    price:       6,
    isSignature: false,
    isPopular:   false,
    heatLevel:   2,
    tags:        ['spicy'],
  },
  {
    id:          'terminator',
    name:        'Terminator',
    category:    'dogs',
    description: 'Chili, Jalapenos, & Diablo Sauce. It will end you.',
    price:       6,
    isSignature: true,
    isPopular:   false,
    heatLevel:   3,
    tags:        ['hot', 'bold'],
  },
  {
    id:          'italian-dawg',
    name:        'Italian Dawg',
    category:    'dogs',
    description: 'Grilled Onions & Green Peppers, Chili, & Mustard.',
    price:       6,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        [],
  },
  {
    id:          'tim-dawg',
    name:        'Tim Dawg',
    category:    'dogs',
    description: 'Peppa Jack Cheese, Cheddar Cheese, Mayo, Ketchup, Mustard, Chili, & Onions.',
    price:       7,
    isSignature: true,
    isPopular:   false,
    heatLevel:   1,
    tags:        ['loaded'],
  },
  {
    id:          'jamaican-jack-dawg',
    name:        'Jamaican Jack Dawg',
    category:    'dogs',
    description: 'Grilled Onions, Chili, Mayo, & Jerk Sauce.',
    price:       6,
    isSignature: true,
    isPopular:   true,
    heatLevel:   2,
    tags:        ['jerk', 'bold', 'bestseller'],
  },
  {
    id:          'hot-honey-dawg',
    name:        'Hot Honey Dawg',
    category:    'dogs',
    description: 'Grilled Onions, Chili, & Hot Honey Sauce. Sweet, heat, drip.',
    price:       6,
    isSignature: true,
    isPopular:   true,
    heatLevel:   2,
    tags:        ['bestseller', 'hot-honey'],
  },
  {
    id:          'mexican-hot-dawg',
    name:        'Mexican Hot Dawg',
    category:    'dogs',
    description: 'Onions, Tomatoes, Jalapenos, Mayo, & Ketchup.',
    price:       6,
    isSignature: false,
    isPopular:   false,
    heatLevel:   1,
    tags:        ['spicy'],
  },

  // ── Wangz ─────────────────────────────────────────────────────────────────────
  {
    id:          'wangz-5',
    name:        '5 Plain Wangz',
    category:    'wangz',
    description: 'Pick any flava below. Add sauce to Wangz, Burgers, or Fries for $1.',
    price:       8,
    isSignature: false,
    isPopular:   true,
    heatLevel:   0,
    flavors: [
      'Dry Ranch', 'BBQ', 'Asian Persuasion', 'Honey Lemon Peppa',
      'Sweet Fire', 'Hot Honey', 'Teriyaki',
      'Spicy Honey Garlic', 'Jamaican Jerk', 'Hot Honey Lemon Peppa',
      'Honey Old Bay', 'Buffalo', 'Buffalo Garlic Parm',
      'Orange Peppa (Wet/Dry)', 'Mango Peppa (Wet/Dry)',
      'Spicy Dry Ranch', 'Garlic Parmesan', 'Buffalo Lemon Peppa',
      'Sweet Chili', 'Honey Mustard', 'Mango Habanero',
    ],
    tags:        ['bestseller'],
  },
  {
    id:          'wangz-10',
    name:        '10 Plain Wangz',
    category:    'wangz',
    description: 'The move. Pick any flava — or mix it up. Add sauce for $1.',
    price:       15,
    isSignature: true,
    isPopular:   true,
    heatLevel:   0,
    flavors: [
      'Dry Ranch', 'BBQ', 'Asian Persuasion', 'Honey Lemon Peppa',
      'Sweet Fire', 'Hot Honey', 'Teriyaki',
      'Spicy Honey Garlic', 'Jamaican Jerk', 'Hot Honey Lemon Peppa',
      'Honey Old Bay', 'Buffalo', 'Buffalo Garlic Parm',
      'Orange Peppa (Wet/Dry)', 'Mango Peppa (Wet/Dry)',
      'Spicy Dry Ranch', 'Garlic Parmesan', 'Buffalo Lemon Peppa',
      'Sweet Chili', 'Honey Mustard', 'Mango Habanero',
    ],
    tags:        ['bestseller', 'shareable'],
  },

  // ── Specialty Fries ───────────────────────────────────────────────────────────
  {
    id:          'regular-fries',
    name:        'Regular Fries',
    category:    'sides',
    description: 'Crispy, straight up.',
    price:       4,
    isSignature: false,
    isPopular:   false,
    heatLevel:   0,
    tags:        ['classic'],
  },
  {
    id:          'spicy-fries',
    name:        'Spicy Fries',
    category:    'sides',
    description: 'Hot Sauce, Jalapenos, Ranch, & Parsley.',
    price:       7,
    isSignature: false,
    isPopular:   false,
    heatLevel:   2,
    tags:        ['spicy'],
  },
  {
    id:          'rollin-fries',
    name:        "Rollin' Fries",
    category:    'sides',
    description: 'Shredded Cheese, Real Bacon, & Ranch.',
    price:       7,
    isSignature: true,
    isPopular:   true,
    heatLevel:   0,
    tags:        ['must-try', 'bestseller'],
  },
  {
    id:          'loaded-fries',
    name:        'Loaded Fries',
    category:    'sides',
    description: 'Homemade Chili & Shredded Cheese.',
    price:       7,
    isSignature: false,
    isPopular:   true,
    heatLevel:   0,
    tags:        ['loaded'],
  },
  {
    id:          'brandon-fries',
    name:        'Brandon Fries',
    category:    'sides',
    description: 'Sweet Fire Sauce, Ranch, Hot Sauce, Jalapenos, & Parsley.',
    price:       8,
    isSignature: true,
    isPopular:   true,
    heatLevel:   2,
    tags:        ['loaded', 'must-try', 'bestseller'],
  },
  {
    id:          'double-loaded-fries',
    name:        'Double Loaded Fries',
    category:    'sides',
    description: 'Homemade Chili, Shredded Cheese, Hot Sauce, Jalapenos, Ranch, & Parsley.',
    price:       9,
    isSignature: true,
    isPopular:   false,
    heatLevel:   2,
    tags:        ['loaded', 'hearty'],
  },
]

export const MENU_CATEGORIES: MenuCategory[] = [
  { id: 'burgers', label: 'Burgers',        emoji: '🍔', description: 'Smashed, stacked, and unapologetic' },
  { id: 'dogs',    label: 'Hot Dawg\'s',    emoji: '🌭', description: 'All-beef. All flavor.' },
  { id: 'wangz',   label: 'Wangz',          emoji: '🍗', description: '21 flavas. You pick the heat.' },
  { id: 'sides',   label: 'Specialty Fries', emoji: '🍟', description: 'The supporting cast that steals the show' },
]

// ─── Condiments ───────────────────────────────────────────────────────────────
// Used in the menu section footer note.

export const CONDIMENTS_FREE = [
  'Ketchup', 'Mayo', 'Onions', 'Jalapenos', 'Lettuce',
  'Relish', 'Mustard', 'Pickles', 'Tomatoes',
] as const

export const CONDIMENTS_EXTRAS = [
  { name: 'Chili',         price: 1 },
  { name: 'Grilled Onions', price: 1 },
  { name: 'Extra Cheese',  price: 1 },
  { name: 'Ranch Cup',     price: 1 },
] as const

// ─── Social Links ─────────────────────────────────────────────────────────────

export const SOCIAL_LINKS: SocialLink[] = [
  {
    platform: 'Facebook',
    handle:   'ROLLINMUNCHIESLLC',
    url:      'https://www.facebook.com/ROLLINMUNCHIESLLC',
    icon:     'facebook',
  },
  {
    platform: 'Instagram',
    handle:   'rollin_munchies',
    url:      'https://www.instagram.com/rollin_munchies',
    icon:     'instagram',
  },
]

// ─── Nav Links ────────────────────────────────────────────────────────────────

export const NAV_LINKS = [
  { label: 'Menu',    href: '#menu'    },
  { label: 'Find Us', href: '#find-us' },
  { label: 'Contact', href: '#contact' },
] as const